[tool.poetry]
name = "simsapa"
version = "0.1.7-alpha.6"
description = "Simsapa Dhamma Reader - Buddhist suttas and Pali dictionary"
# pypi identification
authors = ["Gambhiro <gambhiro.bhikkhu.85@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
PyQt5 = "^5.15.4"
SQLAlchemy = "^1.4.6"
PyYAML = "^5.4.1"
SQLAlchemy-Utils = "^0.37.2"
requests = "^2.25.1"
appdirs = "^1.4.4"
PyPDF2 = "^1.26.0"
epub_meta = "^0.0.7"
PyMuPDF = "^1.18.13"
Pillow = [
  { version = "7.2.0", platform = "linux"},
  { version = "^9.0.0", platform = "win32" },
  { version = "^9.0.0", platform = "darwin" },
]
pandas = "^1.2.4"
openpyxl = "^3.0.7"
semver = "^2.13.0"
pyglossary = "^4.0.11"
lxml = "^4.6.3"
python-dotenv = "^0.17.1"
pyperclip = "^1.8.2"
PyQtWebEngine = "^5.15.4"
networkx = "^2.5.1"
bokeh = "^2.3.2"
alembic = "^1.7.5"
sqlalchemy2-stubs = "^0.0.2-alpha.19"
python-idzip = "^0.3.7"
bleach = "^4.1.0"
Whoosh = "^2.7.4"
typer = "^0.4.0"
tomlkit = "^0.8.0"
feedparser = "^6.0.8"
pyqtkeybind = [{ version = "^0.0.8", platform = "linux" },]

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pyArango = "^1.3.5"

[tool.poetry.scripts]
simsapa = 'simsapa.runner:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.briefcase]
project_name = "Simsapa Dhamma Reader"
bundle = "io.github"
# briefcase requires PEP440 version strings
version = "0.1.7a5"
url = "https://github.com/simsapa/simsapa"
license = "MIT license"
# Package will display this info
author = 'Profound Labs'
author_email = "profound.labs@gmail.com"

[tool.briefcase.app.simsapa]
formal_name = "Simsapa Dhamma Reader"
description = "Buddhist suttas and Pali dictionary"
icon = "simsapa/assets/icons/appicons/simsapa"
sources = ['simsapa']

requires = [
"PyQt5>=5.15.4",
"SQLAlchemy>=1.4.6",
"PyYAML>=5.4.1",
"SQLAlchemy-Utils>=0.37.2",
"requests>=2.25.1",
"appdirs>=1.4.4",
"PyPDF2>=1.26.0",
"epub_meta>=0.0.7",
"PyMuPDF>=1.18.13",
"pandas>=1.2.4",
"openpyxl>=3.0.7",
"semver>=2.13.0",
"pyglossary>=4.0.11",
"lxml>=4.6.3",
"python-dotenv>=0.17.1",
"pyperclip>=1.8.2",
"PyQtWebEngine>=5.15.4",
"networkx>=2.5.1",
"bokeh>=2.3.2",
"alembic>=1.7.5",
"sqlalchemy2-stubs>=0.0.2-alpha.19",
"python-idzip>=0.3.7",
"bleach>=4.1.0",
"Whoosh>=2.7.4",
"typer>=0.4.0",
"tomlkit>=0.8.0",
"feedparser>=6.0.8",
]

[tool.briefcase.app.simsapa.macOS]
requires = ["Pillow>=9.0.0"]

[tool.briefcase.app.simsapa.linux]
requires = [
"Pillow==7.2.0",
"pyqtkeybind>=0.0.8",
]

system_requires = ["libtiff-dev"]

[tool.briefcase.app.simsapa.windows]
requires = ["Pillow>=9.0.0"]

# Mobile deployments
[tool.briefcase.app.simsapa.iOS]
requires = []

[tool.briefcase.app.simsapa.android]
requires = []
