[tool.poetry]
name = "simsapa"
version = "0.2.0-alpha.1"
description = "Simsapa Dhamma Reader - Buddhist suttas and Pali dictionary"
# pypi identification
authors = ["Gambhiro <profound.labs@gmail.com>"]
license = "MIT"

# NOTE: Adjust tool.briefcase.version below.

[simsapa]
db_version = "0.2.0-alpha.1"

[tool.poetry.dependencies]
python = "~3.9"
PyQt6 = "~6.4.0"
PyQt6-WebEngine = "~6.4.0"
PyYAML = "~5.4.1"
SQLAlchemy = "~1.4.44"
SQLAlchemy-Utils = "~0.38.3"
types-sqlalchemy-utils = "~1.0.1"
sqlalchemy2-stubs = "^0.0.2a29"
alembic = "~1.8.1"
requests = "~2"
appdirs = "~1.4.4"
PyPDF2 = "~1.26.0"
epub_meta = "~0.0.7"
PyMuPDF = "~1"
Pillow = "~9.3.0"
#Pillow = [
#  { version = "7.2.0", platform = "linux"},
#  { version = "~9.3.0", platform = "win32" },
#  { version = "~9.3.0", platform = "darwin" },
#]
pandas = "~1"
openpyxl = "~3.0.7"
semver = "~2.13.0"
pyglossary = "~4"
lxml = "~4"
python-dotenv = "~0.17.1"
pyperclip = "~1.8.2"
networkx = "~2"
bokeh = "~2"
scipy = "~1.9.0"
python-idzip = "~0.3.7"
bleach = "~4.1.0"
Whoosh = "~2.7.4"
typer = "~0.4.0"
tomlkit = "~0.8.0"
feedparser = "~6.0.8"
#pyqtkeybind = [{ version = "~0.0.9", platform = "linux" },]
beautifulsoup4 = "~4.10.0"
MarkupSafe = "~2.1.1"
Mako = "~1.1.6"
Flask = "~2.2.2"
Flask-Cors = "~3.0.10"
aksharamukha = "~1.9.7"

[tool.poetry.dev-dependencies]
pytest = "~6.2.5"
pyArango = "~1.3.5"
selenium = "^4.1.1"
lxml = "^4.8.0"
html5lib = "^1.1"

[tool.poetry.scripts]
simsapa = 'simsapa.runner:main'

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.5"
nuitka = "^1.2"
orderedset = "^2.0.3"
scalene = "^1.5.14"
tuna = "^0.5.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "basic"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.briefcase]
project_name = "Simsapa Dhamma Reader"
bundle = "io.github"
# briefcase requires PEP440 version strings
version = "0.2.0a1"
url = "https://github.com/simsapa/simsapa"
license = "MIT license"
# Package will display this info
author = 'Profound Labs'
author_email = "profound.labs@gmail.com"

[tool.briefcase.app.simsapa]
formal_name = "Simsapa Dhamma Reader"
description = "Buddhist suttas and Pali dictionary"
icon = "simsapa/assets/icons/appicons/simsapa"
sources = ['simsapa']

requires = [
"PyQt6              >= 6.4.0,    < 6.5.0",
"PyQt6-WebEngine    >= 6.4.0,    < 6.5.0",
"PyYAML             >= 5.4.1,    < 5.5.0",
"SQLAlchemy         >= 1.4.44,   < 1.5.0",
"SQLAlchemy-Utils   >= 0.38.3,   < 0.39.0",
"types-sqlalchemy-utils >= 1.0.1, < 1.1.0",
"sqlalchemy2-stubs  >= 0.0.2a29, < 0.1.0",
"alembic            >= 1.8.1,    < 1.9.0",
"requests           >= 2.25.0,   < 3.0.0",
"appdirs            >= 1.4.4,    < 1.5.0",
"PyPDF2             >= 1.26.0,   < 1.27.0",
"epub_meta          >= 0.0.7,    < 0.1.0",
"PyMuPDF            >= 1.18.0,   < 2.0.0",
"pandas             >= 1.2.0,    < 2.0.0",
"openpyxl           >= 3.0.7,    < 3.1.0",
"semver             >= 2.13.0,   < 2.14.0",
"pyglossary         >= 4.0.0,    < 5.0.0",
"lxml               >= 4.6.0,    < 5.0.0",
"python-dotenv      >= 0.17.1,   < 0.18.0",
"pyperclip          >= 1.8.2,    < 1.9.0",
"networkx           >= 2.5.0,    < 3.0.0",
"bokeh              >= 2.4.0,    < 3.0.0",
"scipy              >= 1.9.0,    < 2.0.0",
"python-idzip       >= 0.3.7,    < 0.4.0",
"bleach             >= 4.1.0,    < 4.2.0",
"Whoosh             >= 2.7.4,    < 2.8.0",
"typer              >= 0.4.0,    < 0.5.0",
"tomlkit            >= 0.8.0,    < 0.9.0",
"feedparser         >= 6.0.8,    < 6.1.0",
"beautifulsoup4     >= 4.10.0,   < 4.11.0",
"MarkupSafe         == 2.1.1",
"Mako               >= 1.1.6,    < 1.2.0",
"Flask              >= 2.2.2,    < 2.3.0",
"Flask-Cors         >= 3.0.10,   < 3.1.0",
"aksharamukha       >= 1.9.7,    < 1.10.0",
]

[tool.briefcase.app.simsapa.macOS]
requires = [
"Pillow >= 9.3.0, < 9.4.0",
]

[tool.briefcase.app.simsapa.linux]
requires = [
"Pillow >= 9.3.0, < 9.4.0",
#"Pillow == 7.2.0",
#"pyqtkeybind >= 0.0.9, < 0.1.0",
]

system_requires = ["libtiff-dev"]

[tool.briefcase.app.simsapa.windows]
requires = [
"Pillow >= 9.3.0, < 9.4.0",
]

# Mobile deployments
[tool.briefcase.app.simsapa.iOS]
requires = []

[tool.briefcase.app.simsapa.android]
requires = []
