name: Briefcase Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  briefcase:
    name: Bundle on ${{ matrix.platform }} / {{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        os: [Ubuntu, macOS, Windows]
        python-version: ["3.9"]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-2022
          - os: macOS
            image: macos-11
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase
          python -m pip freeze

      - name: Create and Build Bundle
        run: |
          briefcase create
          briefcase build

      - name: Package Mac
        if: runner.os == 'macOS'
        run: briefcase package --no-sign

      - name: Package Windows / Linux
        if: runner.os != 'macOS'
        run: briefcase package

      - name: Upload Artifact for Linux
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: simsapa-${{ runner.os }}.AppImage
          path: '**/*.AppImage'

      - name: Upload Artifact for MacOS
        uses: actions/upload-artifact@v2
        if: runner.os == 'MacOS'
        with:
          name: simsapa-${{ runner.os }}.dmg
          path: '**/*.dmg'

      - name: Upload Artifact for Windows
        uses: actions/upload-artifact@v2
        if: runner.os == 'Windows'
        with:
          name: simsapa-${{ runner.os }}.msi
          path: '**/*.msi'
