name: PyInstaller Build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v[0-9].*'

jobs:
  briefcase:
    name: Bundle on ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, windows-2022]
        python-version: ["3.11"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python pip
        run: python -m pip install --upgrade pip

      - name: Install Python libs
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Linux / Mac Build
        if: runner.os != 'Windows'
        run: |
          pyinstaller run.py --name "Simsapa Dhamma Reader" --onedir -w --clean --noupx -i "simsapa/assets/icons/appicons/simsapa.ico" --add-data "simsapa/assets:simsapa/assets" --add-data "simsapa/alembic:simsapa/alembic" --add-data "simsapa/alembic.ini:simsapa/alembic.ini"

      - name: Windows Build
        if: runner.os == 'Windows'
        run: |
          pyinstaller run.py --name "Simsapa Dhamma Reader" --onedir -w --clean --noupx -i "simsapa\assets\icons\appicons\simsapa.ico" --add-data "simsapa\assets;simsapa\assets" --add-data "simsapa\alembic;simsapa\alembic" --add-data "simsapa\alembic.ini;simsapa\alembic.ini"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: simsapa-${{ github.ref_name }}-${{ matrix.os }}
          path: 'dist/Simsapa Dhamma Reader/'
